name: kimedlung
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.11=hd590300_1
  - anyio=4.2.0=py310h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.2.3=py310h06a4308_1
  - attr=2.5.1=h166bdaf_1
  - backoff=2.2.1=py310h06a4308_1
  - beautifulsoup4=4.12.2=py310h06a4308_0
  - blas=1.0=mkl
  - blessed=1.20.0=py310h06a4308_0
  - boto3=1.29.1=py310h06a4308_0
  - botocore=1.32.1=py310h06a4308_0
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310h06a4308_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - croniter=1.3.7=py310h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.99=0
  - cuda-runtime=12.1.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dateutils=0.6.12=py310h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - dcm2niix=1.0.20240202=h00ab1b0_0
  - deepdiff=6.7.1=py310h2f386ee_0
  - dicom2nifti=2.4.10=pyhd3deb0d_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - eigen=3.4.0=hdb19cb5_0
  - et_xmlfile=1.1.0=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - expat=2.6.1=h59595ed_0
  - fastapi=0.103.0=py310h06a4308_0
  - ffmpeg=4.2.2=h20bf706_0
  - fftw=3.3.10=nompi_hc118613_108
  - filelock=3.13.1=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.10.0=py310h06a4308_0
  - gdcm=2.8.9=py310h59700c5_10
  - gettext=0.21.1=h27087fc_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py310h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.22.9=h8e1006c_0
  - gstreamer=1.22.9=h98fc4e7_0
  - h11=0.14.0=py310h06a4308_0
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdf5=1.14.3=nompi_h4f84152_100
  - icu=73.2=h59595ed_0
  - idna=3.4=py310h06a4308_0
  - importlib_resources=6.1.1=py310h06a4308_1
  - inquirer=3.1.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.1.3=py310h06a4308_0
  - jmespath=1.0.1=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - json-c=0.17=h7ab15ed_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.2=h59595ed_1
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.69=h0f662aa_0
  - libclang=15.0.7=default_hb11cfb5_4
  - libclang13=15.0.7=default_ha2b6cf4_4
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.0.20=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.5.119=0
  - libcurl=8.5.0=hca28451_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.1=h59595ed_0
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgcrypt=1.10.3=hd590300_0
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_5
  - libgpg-error=1.48=h71f35ed_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libitk=5.3.0=h26001f5_8
  - libjpeg-turbo=3.0.0=hd590300_1
  - libllvm15=15.0.7=hb3ce162_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.2=h33b98f1_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.45.1=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libsystemd0=255=h3516f8a_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.6.0=hd429924_1
  - libxml2=2.12.5=h232c23b_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.2.13=hd590300_5
  - lightning=2.0.9.post0=py310h06a4308_0
  - lightning-cloud=0.5.57=py310h06a4308_0
  - lightning-utilities=0.9.0=py310h06a4308_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lxml=5.1.0=py310hcfd0673_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=2.2.0=py310h06a4308_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib=3.8.0=py310h06a4308_0
  - matplotlib-base=3.8.0=py310h1128e8f_0
  - mdurl=0.1.0=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - monai=1.3.0=pyhd8ed1ab_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.4=h59595ed_0
  - mpmath=1.3.0=py310h06a4308_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - nibabel=5.2.1=pyha770c72_0
  - nilearn=0.10.3=pyhd8ed1ab_0
  - nspr=4.35=h6a678d5_0
  - nss=3.98=h1d7d5a4_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h488ebb8_0
  - openpyxl=3.0.10=py310h5eee18b_0
  - openssl=3.2.1=hd590300_1
  - ordered-set=4.1.0=py310h06a4308_0
  - orjson=3.9.10=py310h52d8a92_0
  - packaging=23.2=py310h06a4308_0
  - pandas=2.1.4=py310h1128e8f_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pcre2=10.42=hebb0a14_0
  - pillow=10.2.0=py310h01dd4db_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - ply=3.11=py310h06a4308_0
  - protobuf=3.20.3=py310h6a678d5_0
  - psutil=5.9.0=py310h5eee18b_0
  - pulseaudio-client=16.1=hb77b528_5
  - pydantic=1.10.12=py310h5eee18b_1
  - pydicom=2.4.4=pyhd8ed1ab_0
  - pygments=2.15.1=py310h06a4308_1
  - pyjwt=2.4.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.0=h543edf9_3_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-editor=1.0.4=pyhd3eb1b0_0
  - python-multipart=0.0.6=py310h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=4_cp310
  - pytorch=2.2.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.0.3=py310h06a4308_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py310h06a4308_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - qt-main=5.15.8=h5810be5_19
  - readchar=4.0.5=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_1
  - rich=13.3.5=py310h06a4308_0
  - s3transfer=0.7.0=py310h06a4308_0
  - scikit-learn=1.3.0=py310h1128e8f_1
  - scipy=1.12.0=py310h5f9d8c6_0
  - sentry-sdk=1.9.0=py310h06a4308_0
  - setproctitle=1.2.2=py310h7f8727e_0
  - setuptools=68.2.2=py310h06a4308_0
  - simpleitk=2.3.1=py310hc6cd4ac_2
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - starlette=0.27.0=py310h06a4308_0
  - starsessions=1.3.0=py310h06a4308_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.11.0=h00ab1b0_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py310h06a4308_0
  - torchaudio=2.2.1=py310_cu121
  - torchmetrics=1.1.2=py310h06a4308_0
  - torchtriton=2.2.0=py310
  - torchvision=0.17.1=py310_cu121
  - tornado=6.3.3=py310h5eee18b_0
  - tqdm=4.65.0=py310h2f386ee_0
  - traitlets=5.7.1=py310h06a4308_0
  - typing-extensions=4.9.0=py310h06a4308_1
  - typing_extensions=4.9.0=py310h06a4308_1
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.0.7=py310h06a4308_0
  - uvicorn=0.20.0=py310h06a4308_0
  - wandb=0.16.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=0.58.0=py310h06a4308_4
  - websockets=10.4=py310h5eee18b_1
  - wheel=0.41.2=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.41=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - connected-components-3d==3.12.1
      - imageio==2.34.0
      - lazy-loader==0.3
      - scikit-image==0.22.0
      - tifffile==2024.2.12
prefix: /share/data_rosita1/engelson/miniconda3/envs/kimedlung
